
services:
  dog-api:
    build: .
    container_name: dog-api
    ports:
      - "8080:8080"
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb

    environment:
      MONGO_INITDB_DATABASE: dogdb
    ports:
      - "27018:27017"
    restart: always
    command: ["mongod", "--noauth"]

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
